main:
  - name: "博客"
    weight: 1
    url: "/"
    params:
      tabs:
      - name: "所有文章"
        url: "/"
      - name: "分类"
        url: "/categories/"
      - name: "标签"
        url: "/tags/"
      - name: "归档"
        url: "/archives/"
  - name: "文档"
    weight: 2
    url: "/docs/"
    params:
      tabs:
      - name: "所有文档"
        url: "/docs/"
      - name: "Hugo Stellar"
        url: "/categories/建站/"
  - name: "搜索"
    weight: 3
    url: "/search/"
    params:
      tabs:
      - name: "博客搜索"
        url: "/search/?sec=posts"
      - name: "文档搜索"
        url: "/search/?sec=docs"
  - name: "关于"
    weight: 4
    url: "/about/"
    params:
      tabs:
      - name: "About Hugo"
        url: "/about/#about-hugo"