title: "毕少侠-By stellar"
paginate: 8
relativeURLs: true
#主题配置
theme:
- stellar

markup:
  _merge: deep

params:
  author: 毕少侠
  avatar: /avatar.png
  logo: /logo.svg

  description:
  - "毕少侠也在江湖"
  - "subsubtitle"

  notice:
  - "这是一条公告信息！！！"
  - "支持MD语法"
  - "support `markdown` syntax"

  copyright: "copyright info --- By Geekswg"

  tencentUrl: true
  autoInvert: true

  #社交信息
  social:
  - name: "hugo"
    url: "https://gohugo.io/"
    logo: "/img/social/hugo.svg"
  - name: "github"
    url: "https://github.com/fixit-theme/hugo-blog"
    logo: "/img/social/github.svg"
  - name: "bilibili"
    url: "https://space.bilibili.com/"
    logo: "/img/social/bilibili.svg"
#菜单
menus:
  main:
  - name: "博客"
    weight: 1
    url: "/"
    params:
      tabs:
      - name: "所有文章"
        url: "/"
      - name: "分类"
        url: "/categories/"
      - name: "标签"
        url: "/tags/"
      - name: "归档"
        url: "/archives/"
  - name: "文档"
    weight: 2
    url: "/docs/"
    params:
      tabs:
      - name: "所有文档"
        url: "/docs/"
  - name: "搜索"
    weight: 3
    url: "/search/"
    params:
      tabs:
      - name: "博客搜索"
        url: "/search/?sec=posts"
      - name: "文档搜索"
        url: "/search/?sec=docs"
  - name: "关于"
    weight: 4
    url: "/about/"
    params:
      tabs:
      - name: "About Hugo"
        url: "/about/#about-hugo"
