title: "毕少侠-By stellar"
paginate: 8
relativeURLs: true
#主题配置
theme:
- stellar

markup:
  _merge: deep

params:
  author: 毕少侠
  avatar: /avatar.png
  logo: /logo.svg

  description:
  - "毕少侠也在江湖"
  - "Talk is Cheap, Show me the code."
  - "1234567890"

  notice:
  - "这是一条公告信息！！！"
  - "支持MD语法"
  - "support `markdown` syntax"

  copyright: "copyright@2023 --- By geekswg Powered By [Hugo-stellar](https://github.com/Yharimium/hugo-stellar/) <br/> <a href='https://icp.gov.moe/?keyword=20231992' target='_blank'>萌ICP备20231992号</a>"

  tencentUrl: true
  autoInvert: false

  #社交信息
  social:
  - name: "毕少侠"
    url: "https://geekswg.js.cool/"
    logo: "https://geekswg.js.cool/logo.png"
  - name: "Yharim"
    url: "https://yharim.com/"
    logo: "https://yharim.com/avatar.png"
  - name: "theme"
    url: "https://github.com/Yharimium/hugo-stellar"
    logo: "/avatar.png"
  - name: "hugo"
    url: "https://gohugo.io/"
    logo: "/img/social/hugo.svg"
  - name: "github"
    url: "https://github.com/fixit-theme/hugo-blog"
    logo: "/img/social/github.svg"
  - name: "bilibili"
    url: "https://space.bilibili.com/"
    logo: "/img/social/bilibili.svg"
#菜单
menus:
  main:
  - name: "博客"
    weight: 1
    url: "/"
    params:
      tabs:
      - name: "所有文章"
        url: "/"
      - name: "分类"
        url: "/categories/"
      - name: "标签"
        url: "/tags/"
      - name: "归档"
        url: "/archives/"
  - name: "文档"
    weight: 2
    url: "/docs/"
    params:
      tabs:
      - name: "所有文档"
        url: "/docs/"
      - name: "Hugo Stellar"
        url: "/categories/建站/"
  - name: "搜索"
    weight: 3
    url: "/search/"
    params:
      tabs:
      - name: "博客搜索"
        url: "/search/?sec=posts"
      - name: "文档搜索"
        url: "/search/?sec=docs"
  - name: "关于"
    weight: 4
    url: "/about/"
    params:
      tabs:
      - name: "About Hugo"
        url: "/about/#about-hugo"
