syntax:
- "mkdocs"
- "stellar"

cdn:
  host: "https://cdn.staticfile.org"

  package:
  - link: "host://lxgw-wenkai-screen-webfont/1.1.0/lxgwwenkaiscreen.css"

  - script: "host://jquery/3.6.3/jquery.min.js"

  - script: "host://mermaid/9.4.0/mermaid.js"

  - link: "/modules/fancybox.css"
  - script: "/modules/fancybox.umd.js"
    defer: true

  - script: "/modules/img.js"
    defer: true

  - script: "/modules/toc.js"
    defer: true

  - script: "/modules/codeblock.js"
    defer: true

  - script: "/modules/mathjax.js"
    defer: true
  - script: "host://mathjax/2.7.7/MathJax.js"
    defer: true